version: "3.8"
services:
    db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=pizzas
            - MYSQL_ROOT_PASSWORD=rootuser
        ports:
            - "3306:3306"
        volumes:
            - /db/pizzas:/var/lib/mysql
